export const REGISTER_IN_DOING = 'REGISTER_IN_DOING';
export const REGISTER_IN_DONE = 'REGISTER_IN_DONE';
export const REGISTER_IN_ERROR = 'REGISTER_IN_ERROR';
export const REGISTER_IN_OUT = 'REGISTER_IN_OUT';
export const REGISTER_IN_REGERROR = 'REGISTER_IN_REGERROR';
export const REGISTER_IN_SMSCODE_SUCCESS = 'REGISTER_IN_SMSCODE_SUCCESS';
export const REGISTER_IN_SMSCODE_FAIL = 'REGISTER_IN_SMSCODE_FAIL';
export const REGISTER_IN_PHONESETNULL = 'REGISTER_IN_PHONESETNULL';
